In [2]:
import numpy as np
P = np.array([[1, 7], [2, 1], [3, 1]])
print(P)

[[1 7]
 [2 1]
 [3 1]]


In [3]:
Q = np.array([[1,2], [3,4], [5,6]])

In [4]:
print(P, Q)

[[1 7]
 [2 1]
 [3 1]] [[1 2]
 [3 4]
 [5 6]]


In [7]:
A1 = np.add(P,Q)
print (A1)

[[2 9]
 [5 5]
 [8 7]]


In [8]:
S1 = np.subtract(P,Q)

In [9]:
print(S1)

[[ 0  5]
 [-1 -3]
 [-2 -5]]


In [10]:
R = np.array([[1,2,3],[4,5,6]])

In [12]:
M= np.dot(P, R)

In [17]:
print(M)

[[29 37 45]
 [ 6  9 12]
 [ 7 11 15]]


In [19]:
X = np.array([[1,2],[2,3]])

In [20]:
Det = np.linalg.det(X)

In [21]:
print(Det)

-1.0


In [22]:
Inv = np.linalg.inv(X)
print(Inv)

[[-3.  2.]
 [ 2. -1.]]
