In [2]:
import numpy as np
v = np.array([1,-1,2])
w = np.array([2,5,2])

print (v+w)

[3 4 4]


In [3]:
print(v-w)

[-1 -6  0]


In [4]:
print(3*v)

[ 3 -3  6]


In [5]:
print(np.linalg.norm(v))

2.449489742783178


In [7]:
s = np.dot(v,w)

In [8]:
print(s)

1
